# Generated by Django 2.2.7 on 2021-01-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobseekers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=30)),
                ('skills', models.TextField()),
                ('projectname', models.TextField()),
                ('projectdescription', models.TextField()),
                ('accomplishments', models.TextField()),
            ],
        ),
    ]
