# Generated by Django 2.2.7 on 2021-01-13 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210114_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='emailaddress',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='phonenumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
